// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGD6003-XX3SiDqplKGhDY76vFdUmhYC0',
    appId: '1:164517520209:web:63741b0eb73e3bef02e970',
    messagingSenderId: '164517520209',
    projectId: 'tailoringappointmentapp',
    authDomain: 'tailoringappointmentapp.firebaseapp.com',
    storageBucket: 'tailoringappointmentapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcP3ZgzanHeuTnUVmEmIpqhU49ghccqHU',
    appId: '1:164517520209:android:a0aae9187c130c4a02e970',
    messagingSenderId: '164517520209',
    projectId: 'tailoringappointmentapp',
    storageBucket: 'tailoringappointmentapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC66dns8LmAa3yJT8hIw2jw44QJipboP0k',
    appId: '1:164517520209:ios:5cea1544dfb9bcce02e970',
    messagingSenderId: '164517520209',
    projectId: 'tailoringappointmentapp',
    storageBucket: 'tailoringappointmentapp.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC66dns8LmAa3yJT8hIw2jw44QJipboP0k',
    appId: '1:164517520209:ios:cd6a0de0fbc2c3f202e970',
    messagingSenderId: '164517520209',
    projectId: 'tailoringappointmentapp',
    storageBucket: 'tailoringappointmentapp.appspot.com',
    iosBundleId: 'com.example.newProject.RunnerTests',
  );
}
